import '@/styles/globals.css'
import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { Header } from './components/Header'
import { Footer } from './components/Footer'

import localFont from 'next/font/local'

const blockBerthold = localFont({
  src: './../.././../assets/fonts/block-berthold/Block-Berthold-Regular.ttf',
  display: 'swap',
  variable: '--font-blockBerthold',
})

export const metadata: Metadata = {
  title: 'Landpage | BK',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
}

const BKLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${blockBerthold.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

export default BKLayout
